### PR TITLE
Add Cinder Mac sample project.

### PR DESCRIPTION
**Pull request by kitschpatrol**
Not sure if the "mac" and "dev.mac" configurations are the best way to handle cross-platform launches.

### CODE REVIEW

**Comment by endquote** [comment]
Thank you! I'll take a look.

I think for samples it's probably best to have separate config files for separate platforms, as I did in the [Processing sample](https://github.com/stimulant/ampm/tree/master/samples/processing) (and should do in the web sample). In a production environment you're likely to have multiple configs for multiple machines, but probably not multiple platforms.

**Comment by endquote** [comment]
Looks like there are some project-specific paths in there?
`clang: error: no such file or directory: '/Users/josh/Source/tech-museum-bio.wetlab/Cinder/blocks/OSC/src/Osc.cpp'`

**Comment by kitschpatrol** [comment]
Hey thanks for the feedback. Latest commit switches from embedded to separate platform-specific AMPM config files, and fixes the project-specific path.

**Comment by endquote** [comment]
Sweet, thanks!

**Pull request merged**
